import puppeteer from 'puppeteer';
import { IQuestionPaper } from '../models/QuestionPaper';

export async function generatePDF(
  paper: IQuestionPaper
): Promise<Buffer> {
  const html = buildPaperHTML(paper);

  const browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
});

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });

  const pdf = await page.pdf({
    format: 'A4',
    margin: { top: '18mm', right: '16mm', bottom: '18mm', left: '16mm' },
    printBackground: true,
  });

  await browser.close();
  return Buffer.from(pdf);
}

function buildPaperHTML(p: IQuestionPaper): string {
  const diffColors: Record<string, string> = {
    easy: '#16a34a',
    medium: '#ca8a04',
    hard: '#dc2626',
  };

  let sectionsHTML = '';
  for (const section of p.sections) {
    let questionsHTML = '';
    for (const q of section.questions) {
      let optionsHTML = '';
      if (q.options && q.options.length > 0) {
        optionsHTML = `<div style="display:grid;grid-template-columns:1fr 1fr;gap:3px 20px;margin:6px 0 0 28px;font-size:10.5pt;">
          ${q.options.map((o, i) => `<div>(${String.fromCharCode(97 + i)}) ${o}</div>`).join('')}
        </div>`;
      }
      questionsHTML += `
        <div style="margin:8px 0;padding:6px 0;border-bottom:1px dotted #e5e7eb;">
          <div style="display:flex;align-items:flex-start;gap:6px;">
            <b style="min-width:26px;font-size:11pt;">Q${q.questionNumber}.</b>
            <span style="flex:1;font-size:11pt;line-height:1.5;">${q.text}</span>
            <span style="font-size:7.5pt;padding:2px 7px;border-radius:10px;background:${diffColors[q.difficulty]}15;color:${diffColors[q.difficulty]};border:1px solid ${diffColors[q.difficulty]}30;white-space:nowrap;font-weight:600;text-transform:capitalize;">${q.difficulty}</span>
            <b style="white-space:nowrap;color:#6b7280;font-size:10pt;">[${q.marks}]</b>
          </div>
          ${optionsHTML}
        </div>`;
    }
    sectionsHTML += `
      <div style="margin:14px 0;page-break-inside:avoid;">
        <div style="background:#f8fafc;padding:7px 11px;border:1px solid #e2e8f0;border-radius:6px;margin-bottom:6px;">
          <h3 style="margin:0;font-size:12pt;font-weight:700;">${section.title}</h3>
          <p style="margin:2px 0 0;font-size:9pt;color:#64748b;font-style:italic;">${section.instructions}</p>
        </div>
        ${questionsHTML}
      </div>`;
  }

  const instructionsHTML = p.generalInstructions
    .map((inst) => `<li style="margin:2px 0;">${inst}</li>`)
    .join('');

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:Georgia,'Times New Roman',serif;color:#1a1a1a;font-size:11pt;line-height:1.55;}
</style></head><body style="padding:8px;">
  <div style="text-align:center;border-bottom:3px double #1a1a1a;padding-bottom:10px;margin-bottom:14px;">
    <h1 style="font-size:17pt;margin-bottom:3px;letter-spacing:0.5px;">${p.title}</h1>
    <div style="font-size:11pt;color:#475569;">${p.subject} — Class ${p.grade} (${p.board})</div>
    <div style="display:flex;justify-content:space-between;font-size:10pt;margin-top:8px;color:#334155;">
      <span>Time Allowed: ${p.duration} minutes</span>
      <span>Maximum Marks: ${p.totalMarks}</span>
    </div>
  </div>
  <div style="display:flex;gap:28px;margin:10px 0;padding:9px 12px;background:#fafafa;border:1px solid #e5e7eb;border-radius:4px;">
    <div style="flex:1;font-size:10pt;"><b>Name:</b> <span style="border-bottom:1px solid #999;display:inline-block;min-width:120px;margin-left:4px;">&nbsp;</span></div>
    <div style="flex:1;font-size:10pt;"><b>Roll No:</b> <span style="border-bottom:1px solid #999;display:inline-block;min-width:80px;margin-left:4px;">&nbsp;</span></div>
    <div style="flex:0.6;font-size:10pt;"><b>Section:</b> <span style="border-bottom:1px solid #999;display:inline-block;min-width:50px;margin-left:4px;">&nbsp;</span></div>
  </div>
  <div style="padding:7px 11px;background:#fffbeb;border-left:3px solid #1a1a1a;margin:10px 0;font-size:9.5pt;">
    <b>General Instructions:</b>
    <ol style="padding-left:16px;margin-top:3px;">${instructionsHTML}</ol>
  </div>
  ${sectionsHTML}
  <div style="text-align:center;margin-top:20px;padding-top:10px;border-top:2px solid #1a1a1a;font-size:9pt;color:#9ca3af;">
    — End of Question Paper —<br/>Generated by VedaAI Assessment Creator
  </div>
</body></html>`;
}